name: build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-java@v1
      with:
        java-version: '8'

    - uses: vemonet/setup-spark@v1
      with:
        spark-version: '3.2.1'

    - run: spark-submit --version

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.9'
    - run: conda --version
    - run: which python
    - run: pip3 install pipenv pyspark pytest
    - uses: actions/checkout@v2
    - run: pytest

